theme: jekyll-theme-minimal
title: Ariel E. Kellison
github: is\_project\_page:false
logo: kellison_22.png
description: [ O dear Ophelia!<br> I am ill at these numbers:<br> I have not art to reckon my groans.<br> -HAMLET (Act II, Scene 2, Line 120) <br>- D. Knuth (TACP, Vol 2)}]
