theme: jekyll-theme-minimal
title: Ariel E. Kellison
github: is\_project\_page:false
logo: kellison_22.png
description:  "O dear Ophelia!" 
  "I am ill at these numbers:" 
  "I have not art to reckon my groans."
  "-HAMLET (Act II, Scene 2, Line 120)}"
